#ifndef FTP_ERRORS
#define FTP_ERRORS

enum e_ftp_errors {
	FTP_IVLD_IP,
	FTP_IVLD_ICMP,
	FTP_CHECKSUM_MISMATCH,
	FTP_PAYLOAD_MISMATCH,
	FTP_SEQ_MISMATCH,
	FTP_ID_MISMATCH,
	FTP_IVLD_ICMP_CODE,
	FTP_IVLD_ICMP_TYPE,
	FTP_VALID
};

#define IP_HDR_MAX 60
#define IP_HDR_MIN 20

#endif
